### PR TITLE
add init docsify files

### PR DESCRIPTION
**Pull request by whoabuddy**
This PR will add the .nojekyll and index.html files per the [Quick Start guide](https://docsify.js.org/#/quickstart?id=manual-initialization)

Background: https://github.com/stacksgov/pm/issues/69

### CODE REVIEW

**Comment by whoabuddy** [comment]
I added links to the interview readme, updated the title per the Docsify settings, and enabled another setting for nav. I will have to play with these settings a bit but I think it should satisfy those requests for now!

I also updated the repo description with similar details as the title.

**Comment by lrettig** [comment]
Nice! I think this is probably okay to merge, but the rendered (deployed?) pages at https://stacksgov.github.io/resources/ don't appear to include your latest updates - is there something special we need to do here to rerender/redeploy?

**Comment by lrettig** [comment]
nevermind - I see that it's deployed from master - was able to easily spin up a local server with `docsify serve` - cool!

**Comment by lrettig** [comment]
docsify has issues with relative links in subdirectories - we ran into this at spacemesh too. I fixed the links in the interviews README. the LICENSE link also doesn't work, presumably because the file isn't markdown. close enough, I think, we can always continue to address things as we see them!

**Pull request merged**
