### PR TITLE
update governance and engineering calls

### PR DESCRIPTION
**Pull request by whoabuddy**
This adds governance calls 18 and 19 to the readme table, as well as engineering call 6.

### CODE REVIEW

**Comment by whoabuddy** [comment]
Is the version in 9abe3c5 better? I was debating if it's worth removing the timestamps/whitespace or not.

**Comment by lrettig** [comment]
> Is the version in [9abe3c5](https://github.com/stacksgov/resources/commit/9abe3c5d9d8ad1d8712ccf4a92abd27cc6782407) better? I was debating if it's worth removing the timestamps/whitespace or not.

See for yourself: https://github.com/stacksgov/resources/blob/9abe3c5d9d8ad1d8712ccf4a92abd27cc6782407/calls/notes/2020-07-01-Meeting-0019.md

At least there are linebreaks in this one :)

Let's either use the raw file, or else just rename from .md to .txt to make the format clear.

**Comment by whoabuddy** [comment]
I understand where you are coming from, and it's not that I disagree, just that we've done it differently up to this point and I see some potential issues.

The original file extension and the format in 9abe3c5 represents the `.vtt` file downloaded from Zoom, and while we could change this to `.txt`, the notes format would (hopefully) become a markdown `.md` file once reviewed/updated.

The problem I foresee there is having to update the file name, which also means updating the readme and any other related links, and could lead to more confusion / workflow issues in the long run.

Also, it looks like [Meeting 11](https://github.com/stacksgov/resources/blob/master/calls/notes/2020-05-06-Meeting-0011.md) was the last one to have things revised into markdown format, with [Meeting 12](https://github.com/stacksgov/resources/blob/master/calls/notes/2020-05-13-Meeting-0012.md) representing a raw transcript, and [Meeting 14](https://github.com/stacksgov/resources/blob/master/calls/notes/2020-05-27-Meeting-0014.md), [16](https://github.com/stacksgov/resources/blob/master/calls/notes/2020-06-10-Meeting-0016.md), and [17](https://github.com/stacksgov/resources/blob/master/calls/notes/2020-06-17-Meeting-0017.md) getting butchered by too much regex.

So I would argue that they should stay in markdown format for simplicity, but there is still some bigger picture cleanup that has to happen here, including how to upload the notes in their "initial format" versus a "polished format". The goal was to provide an easy way for the meeting secretary to get us to initial state right after the meeting, then to have a clear issue representing the action (and possibly a bounty) to get us to the polished state.

Maybe we just put a `# YYYYMMDD Governance Meeting Notes` at the top of the file instead so it's technically markdown format, even if the rest is text? :stuck_out_tongue:

**Comment by lrettig** [comment]
works for me. let's keep it simple and not create more work for ourselves - we can always iterate later. will approve this PR!

**Pull request merged**
